#!/bin/bash
curl -s "https://archlinux.org/mirrorlist/?country=JP&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - | sudo tee /etc/pacman.d/mirrorlist
